version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD

  bookstore:
    depends_on:
      - mysqldb
    restart: unless-stopped
    image: bookstore-bookstore
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": 
        "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?
        createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
        &useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC",
        "spring.datasource.username": "$MYSQLDB_USER",
        "spring.datasource.password": "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect": 
        "org.hibernate.dialect.MySQLDialect"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"




