version: '3.8'
services:
  mysqldb:
    image: mysql:8
    restart: on-failure
    env_file: .env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD

  bookstore:
    depends_on:
      - mysqldb
    restart: unless-stopped
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE",
        "spring.datasource.username": "$MYSQLDB_USER",
        "spring.datasource.password": "$MYSQLDB_ROOT_PASSWORD"
      }'




